// Recurrence rules for tasks (docs/plans/13-agenda.md §4, ADR-0013).
//
// ⚠ WHY RRULE AT ALL, AND WHY NOT `rrule.js`. Settled 2026-08-03, and §4's
// warning is the reason it had to be settled BEFORE the migration: changing the
// shape of this column once real chores exist silently reschedules them.
//
// The stored form is an RFC 5545 RRULE string, because it is the standard, it
// is what Google speaks (Piece 3 mirrors Google events), and it can express the
// phrasings dictation actually produces — "the first of the month", "every
// other Tuesday", "the third Monday". `{every, unit}` cannot say any of those.
//
// The LIBRARY was rejected, and the reason is where this file gets its shape:
// the next-three preview has to run live in the browser as you change the
// preset, so `rrule.js` would land tens of kilobytes on a page that currently
// ships almost none. Instead:
//
//   ⚠ EVERY RULE IN THE COLUMN WAS GENERATED BY `rruleFor` BELOW.
//
// The editor sends which PRESET it picked; the action builds the string. So
// this file never has to parse an arbitrary RRULE — only the six shapes it
// wrote itself. `parse` still refuses anything it does not recognise rather
// than guessing, because a rule that expands wrongly is invisible until months
// of chores have been scheduled against it.
//
// If plan 14's parser ever wants a seventh shape, add it HERE with its tests —
// do not relax the validation and let an unexpandable string into the column.
//
// THE ANCHOR IS ALWAYS AN ON-SCHEDULE DATE. Expansion steps FROM an occurrence
// rather than searching a calendar from scratch, which is what keeps
// `INTERVAL=2` in phase: "every 2 weeks" disposed of three weeks late must land
// on the right Monday, not merely on a Monday.
import { shiftYmd, ymdOf, ymdToUtc, type Ymd } from './time';
import { ordinal } from './dates';

/** The six named schedules the editor offers. Nobody hand-writes RRULE (§4). */
export type Preset = 'daily' | 'weekly' | 'biweekly' | 'monthly-date' | 'monthly-nth' | 'weekdays';

export const PRESETS: readonly Preset[] = [
  'daily',
  'weekly',
  'biweekly',
  'monthly-date',
  'monthly-nth',
  'weekdays',
] as const;

const DAY_CODES = ['SU', 'MO', 'TU', 'WE', 'TH', 'FR', 'SA'] as const;
const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as const;

const weekdayOf = (ymd: Ymd) => ymdToUtc(ymd).getUTCDay();
const dayOfMonth = (ymd: Ymd) => ymdToUtc(ymd).getUTCDate();

/**
 * What weekday a local date falls on, in words — `Tuesday`.
 *
 * ⚠ EXPORTED SO `parse-task.ts` STOPS CARRYING ITS OWN (plans/29 · §2, §3). It
 * had a second `WEEKDAY` array, character-identical to `DAY_NAMES` above, in a
 * file that already imports from here — and indexed it with
 * `new Date(\`${ymd}T00:00:00Z\`).getUTCDay()`, which is the raw form
 * `ymdToUtc` exists to replace. Both facts are one fact, so it is one function
 * rather than an exported array and a convention about how to index it.
 */
export function dayNameOf(ymd: Ymd): string {
  return DAY_NAMES[weekdayOf(ymd)];
}

/**
 * Which week of the month a date falls in, as RRULE's `BYDAY` prefix.
 *
 * The 29th, 30th and 31st are the interesting case: "the 5th Monday" happens in
 * some months and not others, so a date in the last week becomes **-1** (the
 * LAST Monday), which every month has. Anything else would give a rule that
 * silently skips most months.
 */
function nthWeekday(ymd: Ymd): number {
  const d = ymdToUtc(ymd);
  const nth = Math.ceil(d.getUTCDate() / 7);
  const daysInMonth = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 0)).getUTCDate();
  return d.getUTCDate() + 7 > daysInMonth ? -1 : nth;
}

/** The RRULE a preset means, anchored on the date the task is due. */
export function rruleFor(preset: Preset, anchor: Ymd): string {
  const dow = DAY_CODES[weekdayOf(anchor)];
  switch (preset) {
    case 'daily':
      return 'FREQ=DAILY';
    case 'weekly':
      return `FREQ=WEEKLY;BYDAY=${dow}`;
    case 'biweekly':
      return `FREQ=WEEKLY;INTERVAL=2;BYDAY=${dow}`;
    case 'monthly-date':
      return `FREQ=MONTHLY;BYMONTHDAY=${dayOfMonth(anchor)}`;
    case 'monthly-nth':
      return `FREQ=MONTHLY;BYDAY=${nthWeekday(anchor)}${dow}`;
    case 'weekdays':
      return 'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR';
  }
}

/**
 * Which preset a stored rule came from — by generating all six for the same
 * anchor and comparing strings.
 *
 * No parser, on purpose: the editor needs to re-select a segment, and matching
 * generated output is exact where a hand-rolled reader of `BYDAY=-1FR` is one
 * more thing that can be subtly wrong. Returns null if nothing matches, which
 * the editor treats as "leave the schedule alone" rather than guessing.
 */
export function presetOf(rrule: string, anchor: Ymd): Preset | null {
  return PRESETS.find((p) => rruleFor(p, anchor) === rrule) ?? null;
}

/** What the preset says on screen — it names the actual day, not a placeholder. */
export function presetLabel(preset: Preset, anchor: Ymd): string {
  const day = DAY_NAMES[weekdayOf(anchor)];
  switch (preset) {
    case 'daily':
      return 'Every day';
    case 'weekly':
      return `Every ${day}`;
    case 'biweekly':
      return `Every other ${day}`;
    case 'monthly-date':
      return `Monthly, on the ${ordinal(dayOfMonth(anchor))}`;
    case 'monthly-nth': {
      const n = nthWeekday(anchor);
      return n === -1 ? `Monthly, on the last ${day}` : `Monthly, on the ${ordinal(n)} ${day}`;
    }
    case 'weekdays':
      return 'Every weekday';
  }
}

// ── expansion ───────────────────────────────────────────────────────────────

interface Rule {
  freq: 'DAILY' | 'WEEKLY' | 'MONTHLY';
  interval: number;
  byday: number[];
  /** For `BYDAY=3MO`: 3, or -1 for the last one. Only with FREQ=MONTHLY. */
  nth: number | null;
  bymonthday: number | null;
}

/**
 * Read one of our own rules back. Deliberately strict — an unrecognised part
 * returns null rather than being ignored, because ignoring a part you did not
 * understand is how a schedule quietly becomes a different schedule.
 */
export function parse(rrule: string): Rule | null {
  const parts = new Map<string, string>();
  for (const chunk of rrule.split(';')) {
    const [k, v] = chunk.split('=');
    if (!k || !v) return null;
    parts.set(k.toUpperCase(), v.toUpperCase());
  }

  const freq = parts.get('FREQ');
  if (freq !== 'DAILY' && freq !== 'WEEKLY' && freq !== 'MONTHLY') return null;

  const interval = parts.has('INTERVAL') ? Number(parts.get('INTERVAL')) : 1;
  if (!Number.isInteger(interval) || interval < 1 || interval > 366) return null;

  const byday: number[] = [];
  let nth: number | null = null;
  const rawDays = parts.get('BYDAY');
  if (rawDays) {
    for (const token of rawDays.split(',')) {
      const m = /^(-?\d)?(SU|MO|TU|WE|TH|FR|SA)$/.exec(token);
      if (!m) return null;
      if (m[1]) {
        // A positional day only means anything monthly, and only one of them.
        if (freq !== 'MONTHLY' || rawDays.includes(',')) return null;
        nth = Number(m[1]);
        if (nth === 0) return null;
      }
      byday.push(DAY_CODES.indexOf(m[2] as (typeof DAY_CODES)[number]));
    }
  }

  let bymonthday: number | null = null;
  const rawDate = parts.get('BYMONTHDAY');
  if (rawDate) {
    bymonthday = Number(rawDate);
    if (!Number.isInteger(bymonthday) || bymonthday < 1 || bymonthday > 31) return null;
    if (freq !== 'MONTHLY' || byday.length) return null;
  }

  for (const key of parts.keys()) {
    if (!['FREQ', 'INTERVAL', 'BYDAY', 'BYMONTHDAY'].includes(key)) return null;
  }
  if (freq === 'MONTHLY' && bymonthday === null && nth === null) return null;

  return { freq, interval, byday, nth, bymonthday };
}

/** Is this a rule we can actually expand? The action's guard on the column. */
export function isSupported(rrule: string): boolean {
  return parse(rrule) !== null;
}

/** The nth (or last) `weekday` of a month, as a local date. */
function nthWeekdayOf(year: number, month: number, weekday: number, nth: number): Ymd | null {
  if (nth > 0) {
    const first = new Date(Date.UTC(year, month, 1));
    const shift = (weekday - first.getUTCDay() + 7) % 7;
    const d = new Date(Date.UTC(year, month, 1 + shift + (nth - 1) * 7));
    return d.getUTCMonth() === month ? ymdOf(d) : null;
  }
  const last = new Date(Date.UTC(year, month + 1, 0));
  const back = (last.getUTCDay() - weekday + 7) % 7;
  return ymdOf(new Date(Date.UTC(year, month, last.getUTCDate() - back)));
}

/**
 * The next occurrence strictly after `from`, where `from` is an on-schedule
 * date (the task's current `due_on`).
 *
 * Stepping from the anchor rather than scanning a calendar is what preserves
 * phase: `INTERVAL=2` from a Monday is always the Monday a fortnight later,
 * however late the disposition happened. If `from` has somehow drifted off the
 * rule — a hand-edited row — the weekly and weekday cases fall forward to the
 * next matching weekday rather than refusing.
 */
export function nextAfter(rrule: string, from: Ymd): Ymd | null {
  const rule = parse(rrule);
  if (!rule) return null;

  if (rule.freq === 'DAILY') return shiftYmd(from, rule.interval);

  if (rule.freq === 'WEEKLY') {
    if (rule.byday.length <= 1) {
      const target = rule.byday[0];
      // On-phase: a whole number of intervals. Off-phase (or no BYDAY at all):
      // walk forward to the next day the rule names.
      if (target === undefined || weekdayOf(from) === target) return shiftYmd(from, 7 * rule.interval);
      let d = shiftYmd(from, 1);
      while (weekdayOf(d) !== target) d = shiftYmd(d, 1);
      return d;
    }
    // A set of weekdays (`weekdays` is MO–FR): simply the next one named.
    let d = shiftYmd(from, 1);
    for (let i = 0; i < 14; i++) {
      if (rule.byday.includes(weekdayOf(d))) return d;
      d = shiftYmd(d, 1);
    }
    return null;
  }

  // MONTHLY. `BYMONTHDAY` follows RFC 5545 and SKIPS a month that has no such
  // date — a chore on the 31st does not happen in February, and the preview is
  // where you see that and change your mind. 24 months is a generous bound for
  // "the next one exists"; nothing we generate can exceed 12.
  const base = ymdToUtc(from);
  for (let i = 1; i <= 24; i++) {
    const year = base.getUTCFullYear();
    const month = base.getUTCMonth() + i * rule.interval;
    if (rule.bymonthday !== null) {
      const d = new Date(Date.UTC(year, month, rule.bymonthday));
      if (d.getUTCDate() === rule.bymonthday) return ymdOf(d);
      continue;
    }
    const anchor = new Date(Date.UTC(year, month, 1));
    const hit = nthWeekdayOf(anchor.getUTCFullYear(), anchor.getUTCMonth(), rule.byday[0], rule.nth!);
    if (hit && hit > from) return hit;
  }
  return null;
}

/**
 * The next `n` occurrences after `from` — the editor's preview, and the only
 * available verification of a rule (§4).
 *
 * You cannot read `FREQ=MONTHLY;BYDAY=3MO` and know it means what you meant,
 * and a recurrence that is subtly wrong stays invisible until months of chores
 * have been scheduled against it. So the panel shows the dates the rule
 * actually produces, and the check is that they look right.
 */
export function nextOccurrences(rrule: string, from: Ymd, n = 3): Ymd[] {
  const out: Ymd[] = [];
  let cursor = from;
  for (let i = 0; i < n; i++) {
    const next = nextAfter(rrule, cursor);
    if (!next) break;
    out.push(next);
    cursor = next;
  }
  return out;
}

// ── after_completion ────────────────────────────────────────────────────────

export type Unit = 'days' | 'weeks' | 'months';

/**
 * "Two weeks after I actually did it."
 *
 * Counted from the day you TICKED it, never from the date it was due — which is
 * the whole point of the mode (§4): with a fixed schedule, finishing a fortnight
 * late leaves you instantly a fortnight behind again, for ever. Months step the
 * calendar rather than adding 30 days, so the 15th stays the 15th.
 */
export function afterCompletion(from: Ymd, every: number, unit: Unit): Ymd {
  if (unit === 'days') return shiftYmd(from, every);
  if (unit === 'weeks') return shiftYmd(from, every * 7);
  const d = ymdToUtc(from);
  const target = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + every, d.getUTCDate()));
  // JS rolls 31 February into March on its own; clamp to the month's last day
  // instead, so "every month" from the 31st does not walk forward a day a year.
  if (target.getUTCDate() !== d.getUTCDate()) target.setUTCDate(0);
  return ymdOf(target);
}
